"""
clan_data.py - Sengoku Period Clan Data for ENGI
All major and notable clans circa 1560, with territories, leaders, and relations.
"""

# ─────────────────────────────────────────────────────────────
# PROVINCE DEFINITIONS (68 historical provinces of Japan)
# Each province maps to a set of region map tiles.
# lat/lon defines the approximate center of each province.
# ─────────────────────────────────────────────────────────────
PROVINCES = {
    # Kinai (Capital Region)
    "yamashiro": {"name": "Yamashiro", "lat": 34.97, "lon": 135.77, "region": "Kinai"},
    "yamato": {"name": "Yamato", "lat": 34.69, "lon": 135.83, "region": "Kinai"},
    "kawachi": {"name": "Kawachi", "lat": 34.60, "lon": 135.60, "region": "Kinai"},
    "izumi": {"name": "Izumi", "lat": 34.50, "lon": 135.45, "region": "Kinai"},
    "settsu": {"name": "Settsu", "lat": 34.72, "lon": 135.30, "region": "Kinai"},
    # Tokaido
    "iga": {"name": "Iga", "lat": 34.77, "lon": 136.13, "region": "Tokaido"},
    "ise": {"name": "Ise", "lat": 34.50, "lon": 136.70, "region": "Tokaido"},
    "shima": {"name": "Shima", "lat": 34.33, "lon": 136.83, "region": "Tokaido"},
    "owari": {"name": "Owari", "lat": 35.18, "lon": 136.91, "region": "Tokaido"},
    "mikawa": {"name": "Mikawa", "lat": 34.95, "lon": 137.18, "region": "Tokaido"},
    "totomi": {"name": "Totomi", "lat": 34.82, "lon": 137.75, "region": "Tokaido"},
    "suruga": {"name": "Suruga", "lat": 35.00, "lon": 138.38, "region": "Tokaido"},
    "izu": {"name": "Izu", "lat": 34.80, "lon": 138.95, "region": "Tokaido"},
    "kai": {"name": "Kai", "lat": 35.66, "lon": 138.57, "region": "Tokaido"},
    "sagami": {"name": "Sagami", "lat": 35.33, "lon": 139.30, "region": "Tokaido"},
    "musashi": {"name": "Musashi", "lat": 35.68, "lon": 139.69, "region": "Tokaido"},
    "awa_boso": {
        "name": "Awa (Boso)",
        "lat": 35.05,
        "lon": 139.95,
        "region": "Tokaido",
    },
    "kazusa": {"name": "Kazusa", "lat": 35.30, "lon": 140.10, "region": "Tokaido"},
    "shimosa": {"name": "Shimosa", "lat": 35.75, "lon": 140.30, "region": "Tokaido"},
    "hitachi": {"name": "Hitachi", "lat": 36.35, "lon": 140.45, "region": "Tokaido"},
    # Tosando
    "omi": {"name": "Omi", "lat": 35.20, "lon": 136.10, "region": "Tosando"},
    "mino": {"name": "Mino", "lat": 35.45, "lon": 136.75, "region": "Tosando"},
    "hida": {"name": "Hida", "lat": 36.20, "lon": 137.25, "region": "Tosando"},
    "shinano": {"name": "Shinano", "lat": 36.23, "lon": 138.18, "region": "Tosando"},
    "kozuke": {"name": "Kozuke", "lat": 36.40, "lon": 139.06, "region": "Tosando"},
    "shimotsuke": {
        "name": "Shimotsuke",
        "lat": 36.55,
        "lon": 139.88,
        "region": "Tosando",
    },
    "mutsu": {"name": "Mutsu", "lat": 39.70, "lon": 141.15, "region": "Tosando"},
    "dewa": {"name": "Dewa", "lat": 39.00, "lon": 140.00, "region": "Tosando"},
    # Hokurikudo
    "wakasa": {"name": "Wakasa", "lat": 35.50, "lon": 135.80, "region": "Hokurikudo"},
    "echizen": {"name": "Echizen", "lat": 36.07, "lon": 136.22, "region": "Hokurikudo"},
    "kaga": {"name": "Kaga", "lat": 36.57, "lon": 136.63, "region": "Hokurikudo"},
    "noto": {"name": "Noto", "lat": 37.10, "lon": 136.90, "region": "Hokurikudo"},
    "etchu": {"name": "Etchu", "lat": 36.70, "lon": 137.20, "region": "Hokurikudo"},
    "echigo": {"name": "Echigo", "lat": 37.90, "lon": 139.02, "region": "Hokurikudo"},
    "sado": {"name": "Sado", "lat": 38.05, "lon": 138.35, "region": "Hokurikudo"},
    # San'indo
    "tamba": {"name": "Tamba", "lat": 35.10, "lon": 135.40, "region": "Sanindo"},
    "tango": {"name": "Tango", "lat": 35.55, "lon": 135.10, "region": "Sanindo"},
    "tajima": {"name": "Tajima", "lat": 35.40, "lon": 134.80, "region": "Sanindo"},
    "inaba": {"name": "Inaba", "lat": 35.50, "lon": 134.24, "region": "Sanindo"},
    "hoki": {"name": "Hoki", "lat": 35.45, "lon": 133.70, "region": "Sanindo"},
    "izumo": {"name": "Izumo", "lat": 35.40, "lon": 132.75, "region": "Sanindo"},
    "iwami": {"name": "Iwami", "lat": 34.95, "lon": 132.10, "region": "Sanindo"},
    "oki": {"name": "Oki", "lat": 36.20, "lon": 133.10, "region": "Sanindo"},
    # San'yodo
    "harima": {"name": "Harima", "lat": 34.85, "lon": 134.70, "region": "Sanyodo"},
    "mimasaka": {"name": "Mimasaka", "lat": 35.05, "lon": 134.00, "region": "Sanyodo"},
    "bizen": {"name": "Bizen", "lat": 34.75, "lon": 134.05, "region": "Sanyodo"},
    "bitchu": {"name": "Bitchu", "lat": 34.68, "lon": 133.60, "region": "Sanyodo"},
    "bingo": {"name": "Bingo", "lat": 34.60, "lon": 133.10, "region": "Sanyodo"},
    "aki": {"name": "Aki", "lat": 34.39, "lon": 132.46, "region": "Sanyodo"},
    "suo": {"name": "Suo", "lat": 34.18, "lon": 131.80, "region": "Sanyodo"},
    "nagato": {"name": "Nagato", "lat": 34.20, "lon": 131.47, "region": "Sanyodo"},
    # Nankaido
    "kii": {"name": "Kii", "lat": 33.85, "lon": 135.70, "region": "Nankaido"},
    "awaji": {"name": "Awaji", "lat": 34.45, "lon": 134.90, "region": "Nankaido"},
    "awa_shikoku": {
        "name": "Awa (Shikoku)",
        "lat": 34.07,
        "lon": 134.55,
        "region": "Nankaido",
    },
    "sanuki": {"name": "Sanuki", "lat": 34.30, "lon": 134.00, "region": "Nankaido"},
    "iyo": {"name": "Iyo", "lat": 33.84, "lon": 132.77, "region": "Nankaido"},
    "tosa": {"name": "Tosa", "lat": 33.56, "lon": 133.53, "region": "Nankaido"},
    # Saikaido (Kyushu)
    "chikuzen": {"name": "Chikuzen", "lat": 33.59, "lon": 130.41, "region": "Saikaido"},
    "chikugo": {"name": "Chikugo", "lat": 33.20, "lon": 130.55, "region": "Saikaido"},
    "buzen": {"name": "Buzen", "lat": 33.65, "lon": 131.00, "region": "Saikaido"},
    "bungo": {"name": "Bungo", "lat": 33.24, "lon": 131.61, "region": "Saikaido"},
    "hizen": {"name": "Hizen", "lat": 33.20, "lon": 129.90, "region": "Saikaido"},
    "higo": {"name": "Higo", "lat": 32.80, "lon": 130.74, "region": "Saikaido"},
    "hyuga": {"name": "Hyuga", "lat": 31.91, "lon": 131.42, "region": "Saikaido"},
    "osumi": {"name": "Osumi", "lat": 31.40, "lon": 130.90, "region": "Saikaido"},
    "satsuma": {"name": "Satsuma", "lat": 31.60, "lon": 130.56, "region": "Saikaido"},
    "tsushima": {"name": "Tsushima", "lat": 34.40, "lon": 129.35, "region": "Saikaido"},
    "iki": {"name": "Iki", "lat": 33.75, "lon": 129.75, "region": "Saikaido"},
    # Hokkaido (Ezo)
    "ezo": {"name": "Ezo (Hokkaido)", "lat": 43.00, "lon": 141.35, "region": "Ezo"},
}

# ─────────────────────────────────────────────────────────────
# CLAN DEFINITIONS (~55 notable Sengoku-era clans, circa 1560)
# ─────────────────────────────────────────────────────────────
# Each clan has:
#   name: display name (Japanese + English)
#   daimyo: name of the clan leader circa 1560
#   capital: primary castle/city
#   provinces: list of province keys controlled at start
#   military: relative military strength (1-100)
#   treasury: starting wealth (mon)
#   allies: list of clan keys they start allied with
#   enemies: list of clan keys they start hostile toward
#   traits: list of special traits affecting behavior
#   color: display color pair
#   mon: clan emblem description
#   desc: brief historical description

CLANS = {
    # ── Major Clans (top-tier power) ──────────────────────
    "oda": {
        "name": "織田 Oda",
        "daimyo": "Oda Nobunaga",
        "capital": "Nagoya",
        "provinces": ["owari"],
        "military": 75,
        "treasury": 5000,
        "allies": ["tokugawa"],
        "enemies": ["imagawa", "saito"],
        "traits": ["innovative", "aggressive", "gunpowder"],
        "color": 5,
        "mon": "Oda mokko (five-petaled wood sorrel)",
        "desc": "The Demon King rises. Nobunaga will reshape Japan or burn it trying.",
    },
    "tokugawa": {
        "name": "徳川 Tokugawa",
        "daimyo": "Tokugawa Ieyasu",
        "capital": "Edo",
        "provinces": ["mikawa", "musashi"],
        "military": 65,
        "treasury": 4000,
        "allies": ["oda"],
        "enemies": ["imagawa", "takeda"],
        "traits": ["patient", "defensive", "diplomatic"],
        "color": 4,
        "mon": "Tokugawa aoi (triple hollyhock)",
        "desc": "The patient turtle. Ieyasu waits while others overextend.",
    },
    "takeda": {
        "name": "武田 Takeda",
        "daimyo": "Takeda Shingen",
        "capital": "Kofu",
        "provinces": ["kai", "shinano"],
        "military": 85,
        "treasury": 3500,
        "allies": ["hojo"],
        "enemies": ["uesugi", "tokugawa"],
        "traits": ["cavalry", "aggressive", "mountain_warfare"],
        "color": 5,
        "mon": "Takeda bishi (four diamonds)",
        "desc": "The Tiger of Kai. Finest cavalry in Japan. Feared by all neighbors.",
    },
    "uesugi": {
        "name": "上杉 Uesugi",
        "daimyo": "Uesugi Kenshin",
        "capital": "Niigata",
        "provinces": ["echigo", "sado"],
        "military": 80,
        "treasury": 3000,
        "allies": [],
        "enemies": ["takeda", "hojo"],
        "traits": ["honorable", "aggressive", "winter_warfare"],
        "color": 4,
        "mon": "Uesugi sasarindou (bamboo and gentian)",
        "desc": "The Dragon of Echigo. God of War incarnate. Rival of Shingen.",
    },
    "hojo": {
        "name": "北条 Hojo",
        "daimyo": "Hojo Ujiyasu",
        "capital": "Odawara",
        "provinces": ["sagami", "izu", "shimosa", "kazusa"],
        "military": 70,
        "treasury": 6000,
        "allies": ["takeda"],
        "enemies": ["uesugi", "satomi"],
        "traits": ["defensive", "administrative", "castle_builders"],
        "color": 7,
        "mon": "Hojo uroko (three scales)",
        "desc": "Masters of the Kanto. Odawara castle has never fallen.",
    },
    "mori": {
        "name": "毛利 Mori",
        "daimyo": "Mori Motonari",
        "capital": "Hiroshima",
        "provinces": ["aki", "bingo", "suo", "nagato", "iwami", "izumo"],
        "military": 75,
        "treasury": 5000,
        "allies": [],
        "enemies": ["amago", "otomo"],
        "traits": ["diplomatic", "naval", "cunning"],
        "color": 2,
        "mon": "Mori ichimonji ni mitsuboshi (one line, three stars)",
        "desc": "From one province to ten. Motonari the strategist swallowed western Honshu.",
    },
    "shimazu": {
        "name": "島津 Shimazu",
        "daimyo": "Shimazu Takahisa",
        "capital": "Kagoshima",
        "provinces": ["satsuma", "osumi"],
        "military": 80,
        "treasury": 3500,
        "allies": [],
        "enemies": ["otomo", "ito"],
        "traits": ["aggressive", "gunpowder", "fierce"],
        "color": 5,
        "mon": "Shimazu jumonji (cross in circle)",
        "desc": "Southern warriors. First to adopt Portuguese firearms. Utterly fearless.",
    },
    "toyotomi": {
        "name": "豊臣 Toyotomi",
        "daimyo": "Toyotomi Hideyoshi",
        "capital": "Osaka",
        "provinces": [],
        "military": 10,
        "treasury": 100,
        "allies": ["oda"],
        "enemies": [],
        "traits": ["charismatic", "cunning", "low_born"],
        "color": 3,
        "mon": "Toyotomi paulownia (five-seven paulownia)",
        "desc": "A sandal-bearer's son. Not yet risen. Watch this one.",
    },
    # ── Strong Regional Clans ─────────────────────────────
    "imagawa": {
        "name": "今川 Imagawa",
        "daimyo": "Imagawa Yoshimoto",
        "capital": "Shizuoka",
        "provinces": ["suruga", "totomi"],
        "military": 60,
        "treasury": 4000,
        "allies": ["takeda_pre"],
        "enemies": ["oda", "tokugawa"],
        "traits": ["cultured", "aristocratic"],
        "color": 6,
        "mon": "Imagawa akadori (red bird)",
        "desc": "Aristocratic lords of Suruga. Marching west with 25,000 men. What could go wrong?",
    },
    "date": {
        "name": "伊達 Date",
        "daimyo": "Date Terumune",
        "capital": "Sendai",
        "provinces": ["mutsu"],
        "military": 65,
        "treasury": 3000,
        "allies": [],
        "enemies": ["ashina"],
        "traits": ["aggressive", "independent"],
        "color": 4,
        "mon": "Date sendai sasarindou (bamboo sparrow)",
        "desc": "Northern dragons. Masamune (the son) will be the One-Eyed Dragon.",
    },
    "chosokabe": {
        "name": "長宗我部 Chosokabe",
        "daimyo": "Chosokabe Motochika",
        "capital": "Kochi",
        "provinces": ["tosa"],
        "military": 55,
        "treasury": 2000,
        "allies": [],
        "enemies": ["miyoshi"],
        "traits": ["aggressive", "farmer_warriors"],
        "color": 2,
        "mon": "Chosokabe seven stars",
        "desc": "Tosa Province. Motochika dreams of unifying all four Shikoku provinces.",
    },
    "otomo": {
        "name": "大友 Otomo",
        "daimyo": "Otomo Sorin",
        "capital": "Oita",
        "provinces": ["bungo", "buzen"],
        "military": 55,
        "treasury": 3000,
        "allies": [],
        "enemies": ["shimazu", "mori"],
        "traits": ["christian", "gunpowder", "trade"],
        "color": 6,
        "mon": "Otomo apricot blossom",
        "desc": "Christian daimyo of Bungo. Portuguese cannon and Jesuit advisors.",
    },
    "saito": {
        "name": "斎藤 Saito",
        "daimyo": "Saito Yoshitatsu",
        "capital": "Gifu",
        "provinces": ["mino"],
        "military": 45,
        "treasury": 2500,
        "allies": [],
        "enemies": ["oda"],
        "traits": ["defensive"],
        "color": 7,
        "mon": "Saito nadeshiko (fringed pink)",
        "desc": "Mino Province. The Viper's heirs cling to power as Nobunaga circles.",
    },
    "maeda": {
        "name": "前田 Maeda",
        "daimyo": "Maeda Toshiie",
        "capital": "Kanazawa",
        "provinces": ["kaga", "noto"],
        "military": 50,
        "treasury": 4500,
        "allies": ["oda"],
        "enemies": [],
        "traits": ["wealthy", "diplomatic", "cultured"],
        "color": 3,
        "mon": "Maeda ume bachi (plum blossom)",
        "desc": "Kaga million-koku domain. Rivaling Kyoto in wealth and culture.",
    },
    "satake": {
        "name": "佐竹 Satake",
        "daimyo": "Satake Yoshishige",
        "capital": "Akita",
        "provinces": ["hitachi"],
        "military": 45,
        "treasury": 2000,
        "allies": ["uesugi"],
        "enemies": ["hojo"],
        "traits": ["traditional"],
        "color": 4,
        "mon": "Satake fan",
        "desc": "Ancient Hitachi lords. Allied with the Dragon of Echigo against Hojo.",
    },
    # ── Medium Clans ──────────────────────────────────────
    "nanbu": {
        "name": "南部 Nanbu",
        "daimyo": "Nanbu Harumasa",
        "capital": "Morioka",
        "provinces": [],
        "military": 35,
        "treasury": 1500,
        "allies": [],
        "enemies": ["tsugaru"],
        "traits": ["horse_breeding"],
        "color": 7,
        "mon": "Nanbu crane",
        "desc": "Northern horse breeders. Remote but resilient.",
    },
    "tsugaru": {
        "name": "津軽 Tsugaru",
        "daimyo": "Tsugaru Tamenobu",
        "capital": "Aomori",
        "provinces": [],
        "military": 25,
        "treasury": 1000,
        "allies": [],
        "enemies": ["nanbu"],
        "traits": ["independent"],
        "color": 7,
        "mon": "Tsugaru peony",
        "desc": "Aomori frontier. Carved independence from the Nanbu by force.",
    },
    "mogami": {
        "name": "最上 Mogami",
        "daimyo": "Mogami Yoshiaki",
        "capital": "Yamagata",
        "provinces": ["dewa"],
        "military": 40,
        "treasury": 2000,
        "allies": [],
        "enemies": ["date"],
        "traits": ["cunning", "trade"],
        "color": 7,
        "mon": "Mogami bamboo sparrow",
        "desc": "Dewa Province silver mines. Wealthy but surrounded by wolves.",
    },
    "ashina": {
        "name": "蘆名 Ashina",
        "daimyo": "Ashina Moriuji",
        "capital": "Aizu",
        "provinces": [],
        "military": 35,
        "treasury": 1500,
        "allies": [],
        "enemies": ["date"],
        "traits": ["defensive"],
        "color": 7,
        "mon": "Ashina three-pronged fork",
        "desc": "Aizu mountain fortress clan. Standing against Date expansion.",
    },
    "uesugi_hatakeyama": {
        "name": "畠山 Hatakeyama",
        "daimyo": "Hatakeyama Yoshitsugu",
        "capital": "Noto",
        "provinces": [],
        "military": 20,
        "treasury": 1000,
        "allies": [],
        "enemies": [],
        "traits": ["declining"],
        "color": 8,
        "mon": "Hatakeyama two-drawn bow",
        "desc": "Once powerful Noto lords. Now in terminal decline.",
    },
    "asakura": {
        "name": "朝倉 Asakura",
        "daimyo": "Asakura Yoshikage",
        "capital": "Ichijodani",
        "provinces": ["echizen"],
        "military": 45,
        "treasury": 2500,
        "allies": [],
        "enemies": ["oda"],
        "traits": ["cultured", "defensive"],
        "color": 2,
        "mon": "Asakura triple comma",
        "desc": "Echizen lords. Cultural capital but militarily stagnant.",
    },
    "azai": {
        "name": "浅井 Azai",
        "daimyo": "Azai Nagamasa",
        "capital": "Odani",
        "provinces": ["omi"],
        "military": 35,
        "treasury": 2000,
        "allies": ["asakura"],
        "enemies": [],
        "traits": ["honorable"],
        "color": 3,
        "mon": "Azai mitsu-domoe (triple comma)",
        "desc": "Omi Province. Nobunaga's brother-in-law. Torn loyalties ahead.",
    },
    "rokkaku": {
        "name": "六角 Rokkaku",
        "daimyo": "Rokkaku Yoshikata",
        "capital": "Kannonji",
        "provinces": [],
        "military": 25,
        "treasury": 1500,
        "allies": [],
        "enemies": ["azai", "oda"],
        "traits": ["declining"],
        "color": 8,
        "mon": "Rokkaku yotsume (four eyes)",
        "desc": "Southern Omi. Once controlled the road to Kyoto.",
    },
    "miyoshi": {
        "name": "三好 Miyoshi",
        "daimyo": "Miyoshi Nagayoshi",
        "capital": "Tokushima",
        "provinces": ["awa_shikoku", "settsu"],
        "military": 45,
        "treasury": 3000,
        "allies": [],
        "enemies": ["chosokabe"],
        "traits": ["political"],
        "color": 7,
        "mon": "Miyoshi rhombus",
        "desc": "Controlled Kyoto briefly. Now fragmenting after Nagayoshi's death.",
    },
    "kono": {
        "name": "河野 Kono",
        "daimyo": "Kono Michinao",
        "capital": "Matsuyama",
        "provinces": ["iyo"],
        "military": 25,
        "treasury": 1500,
        "allies": [],
        "enemies": ["chosokabe"],
        "traits": ["naval"],
        "color": 4,
        "mon": "Kono folding fan",
        "desc": "Iyo naval lords. The Inland Sea is their highway.",
    },
    "kuroda": {
        "name": "黒田 Kuroda",
        "daimyo": "Kuroda Yoshitaka",
        "capital": "Fukuoka",
        "provinces": ["chikuzen"],
        "military": 40,
        "treasury": 2500,
        "allies": ["toyotomi"],
        "enemies": [],
        "traits": ["strategic", "diplomatic"],
        "color": 7,
        "mon": "Kuroda fuji (wisteria)",
        "desc": "Brilliant strategist clan. Yoshitaka's mind is the sharpest blade.",
    },
    "arima": {
        "name": "有馬 Arima",
        "daimyo": "Arima Yoshisada",
        "capital": "Nagasaki",
        "provinces": ["hizen"],
        "military": 25,
        "treasury": 3000,
        "allies": ["otomo"],
        "enemies": ["ryuzoji"],
        "traits": ["christian", "trade"],
        "color": 6,
        "mon": "Arima paulownia",
        "desc": "Christian lords of Hizen. Portuguese trade flows through their port.",
    },
    "ryuzoji": {
        "name": "龍造寺 Ryuzoji",
        "daimyo": "Ryuzoji Takanobu",
        "capital": "Saga",
        "provinces": [],
        "military": 45,
        "treasury": 2000,
        "allies": [],
        "enemies": ["arima", "shimazu"],
        "traits": ["aggressive", "fierce"],
        "color": 5,
        "mon": "Ryuzoji twelve sun",
        "desc": "The Bear of Hizen. Expanding rapidly through raw force.",
    },
    "kato": {
        "name": "加藤 Kato",
        "daimyo": "Kato Kiyomasa",
        "capital": "Kumamoto",
        "provinces": ["higo"],
        "military": 50,
        "treasury": 2000,
        "allies": ["toyotomi"],
        "enemies": [],
        "traits": ["castle_builders", "aggressive"],
        "color": 5,
        "mon": "Kato snake-eye",
        "desc": "Higo Province. Kiyomasa builds castles that will stand for centuries.",
    },
    "ito": {
        "name": "伊東 Ito",
        "daimyo": "Ito Yoshisuke",
        "capital": "Obi",
        "provinces": ["hyuga"],
        "military": 30,
        "treasury": 1500,
        "allies": [],
        "enemies": ["shimazu"],
        "traits": [],
        "color": 7,
        "mon": "Ito crane",
        "desc": "Hyuga Province. Caught between the Shimazu hammer and the Otomo anvil.",
    },
    "matsumae": {
        "name": "松前 Matsumae",
        "daimyo": "Kakizaki Suehiro",
        "capital": "Matsumae",
        "provinces": ["ezo"],
        "military": 20,
        "treasury": 1000,
        "allies": [],
        "enemies": [],
        "traits": ["trade", "frontier"],
        "color": 7,
        "mon": "Matsumae maru ni mitsubaaoi",
        "desc": "Ezo frontier lords. Trading with the Ainu at the edge of the known world.",
    },
    # ── Minor but Notable Clans ───────────────────────────
    "satomi": {
        "name": "里見 Satomi",
        "daimyo": "Satomi Yoshitaka",
        "capital": "Tateyama",
        "provinces": ["awa_boso"],
        "military": 25,
        "treasury": 1200,
        "allies": [],
        "enemies": ["hojo"],
        "traits": ["naval"],
        "color": 4,
        "mon": "Satomi two bamboo sparrows",
        "desc": "Awa (Boso) naval lords. Defending against Hojo encroachment.",
    },
    "tsutsui": {
        "name": "筒井 Tsutsui",
        "daimyo": "Tsutsui Junkei",
        "capital": "Nara",
        "provinces": ["yamato"],
        "military": 20,
        "treasury": 1500,
        "allies": [],
        "enemies": [],
        "traits": ["opportunistic"],
        "color": 6,
        "mon": "Tsutsui crest",
        "desc": "Yamato temple warrior clan. Watch which way the wind blows, then follow.",
    },
    "hosokawa": {
        "name": "細川 Hosokawa",
        "daimyo": "Hosokawa Fujitaka",
        "capital": "Tango",
        "provinces": ["tango"],
        "military": 30,
        "treasury": 2000,
        "allies": ["oda"],
        "enemies": [],
        "traits": ["cultured", "diplomatic"],
        "color": 6,
        "mon": "Hosokawa nine planets",
        "desc": "Master of culture, poetry, and martial arts. A Renaissance daimyo.",
    },
    "bessho": {
        "name": "別所 Bessho",
        "daimyo": "Bessho Nagaharu",
        "capital": "Miki",
        "provinces": ["harima"],
        "military": 25,
        "treasury": 1500,
        "allies": [],
        "enemies": ["oda"],
        "traits": ["defensive"],
        "color": 8,
        "mon": "Bessho crest",
        "desc": "Harima fortress lords. Miki castle will face a terrible siege.",
    },
    "amago": {
        "name": "尼子 Amago",
        "daimyo": "Amago Yoshihisa",
        "capital": "Gassan-Toda",
        "provinces": ["hoki", "inaba"],
        "military": 35,
        "treasury": 2000,
        "allies": [],
        "enemies": ["mori"],
        "traits": ["defensive", "declining"],
        "color": 8,
        "mon": "Amago four-eyed square",
        "desc": "Once ruled all San'in. Now fighting extinction against the Mori tide.",
    },
    "ukita": {
        "name": "宇喜多 Ukita",
        "daimyo": "Ukita Naoie",
        "capital": "Okayama",
        "provinces": ["bizen"],
        "military": 35,
        "treasury": 2000,
        "allies": ["mori"],
        "enemies": [],
        "traits": ["cunning", "assassination"],
        "color": 7,
        "mon": "Ukita sword in circle",
        "desc": "Bizen Province. Naoie rose through poison and betrayal.",
    },
    "murakami_navy": {
        "name": "村上 Murakami",
        "daimyo": "Murakami Takeyoshi",
        "capital": "Innoshima",
        "provinces": [],
        "military": 30,
        "treasury": 3000,
        "allies": ["mori"],
        "enemies": [],
        "traits": ["naval", "pirate"],
        "color": 4,
        "mon": "Murakami maruni mitsuboshi",
        "desc": "The Murakami Navy. Sea lords of the Inland Sea. Pirates or protectors.",
    },
    "sanada": {
        "name": "真田 Sanada",
        "daimyo": "Sanada Masayuki",
        "capital": "Ueda",
        "provinces": [],
        "military": 25,
        "treasury": 1000,
        "allies": ["takeda"],
        "enemies": ["tokugawa"],
        "traits": ["cunning", "guerilla", "mountain_warfare"],
        "color": 5,
        "mon": "Sanada rokumonsen (six coins)",
        "desc": "Six coins for the ferryman. Small but brilliant. Tokugawa will learn to hate this name.",
    },
    "ikko_ikki": {
        "name": "一向一揆 Ikko-ikki",
        "daimyo": "Kennyo Kosa",
        "capital": "Ishiyama Honganji",
        "provinces": ["kawachi", "kaga"],
        "military": 60,
        "treasury": 4000,
        "allies": [],
        "enemies": ["oda"],
        "traits": ["religious", "fanatic", "peasant_army"],
        "color": 3,
        "mon": "Ikko-ikki chrysanthemum",
        "desc": "Buddhist warrior monks and armed peasants. The Realm of the Buddha on earth.",
    },
    "negoro": {
        "name": "根来 Negoro",
        "daimyo": "Temple Abbot",
        "capital": "Negoroji",
        "provinces": ["kii"],
        "military": 35,
        "treasury": 2000,
        "allies": ["ikko_ikki"],
        "enemies": ["oda"],
        "traits": ["religious", "gunpowder"],
        "color": 6,
        "mon": "Negoro temple crest",
        "desc": "Warrior monks of Kii. Masters of the teppo. An arsenal disguised as a temple.",
    },
    "saika": {
        "name": "雑賀 Saika",
        "daimyo": "Saika Magoichi",
        "capital": "Saika",
        "provinces": [],
        "military": 30,
        "treasury": 1500,
        "allies": ["ikko_ikki", "negoro"],
        "enemies": ["oda"],
        "traits": ["gunpowder", "mercenary"],
        "color": 5,
        "mon": "Saika yatagarasu (three-legged crow)",
        "desc": "Mercenary gunners. The deadliest marksmen in Japan. Magoichi never misses.",
    },
    "imperial": {
        "name": "朝廷 Imperial Court",
        "daimyo": "Emperor Ogimachi",
        "capital": "Kyoto",
        "provinces": ["yamashiro"],
        "military": 5,
        "treasury": 500,
        "allies": [],
        "enemies": [],
        "traits": ["legitimate", "cultured", "powerless"],
        "color": 6,
        "mon": "Imperial chrysanthemum (sixteen petals)",
        "desc": "The Emperor rules in name only. Behind silk screens, real power lies elsewhere.",
    },
}

# ─────────────────────────────────────────────────────────────
# CLAN RELATION TYPES
# ─────────────────────────────────────────────────────────────
RELATION_ALLIED = "allied"
RELATION_FRIENDLY = "friendly"
RELATION_NEUTRAL = "neutral"
RELATION_HOSTILE = "hostile"
RELATION_WAR = "at_war"
RELATION_TRUCE = "truce"
RELATION_VASSAL = "vassal"

# ─────────────────────────────────────────────────────────────
# CLAN TRAIT EFFECTS
# ─────────────────────────────────────────────────────────────
CLAN_TRAITS = {
    "aggressive": {
        "war_tendency": 1.5,
        "expansion_rate": 1.3,
        "desc": "More likely to declare war.",
    },
    "defensive": {
        "war_tendency": 0.5,
        "defense_bonus": 1.3,
        "desc": "Prefers to hold territory.",
    },
    "diplomatic": {
        "alliance_rate": 1.5,
        "truce_rate": 1.3,
        "desc": "Forms alliances more readily.",
    },
    "patient": {
        "war_tendency": 0.3,
        "opportunism": 1.5,
        "desc": "Waits for the perfect moment.",
    },
    "innovative": {"tech_rate": 1.5, "desc": "Adopts new tactics and weapons quickly."},
    "gunpowder": {"ranged_bonus": 1.4, "desc": "Skilled with firearms."},
    "cavalry": {"cavalry_bonus": 1.5, "desc": "Superior mounted warfare."},
    "naval": {"naval_bonus": 1.5, "desc": "Controls sea lanes."},
    "cunning": {
        "assassination_rate": 1.3,
        "espionage": 1.3,
        "desc": "Uses subterfuge.",
    },
    "cultured": {
        "morale_bonus": 1.2,
        "diplomacy_bonus": 1.2,
        "desc": "High culture boosts morale.",
    },
    "honorable": {
        "morale_bonus": 1.3,
        "betrayal_rate": 0.1,
        "desc": "Rarely breaks alliances.",
    },
    "fierce": {
        "attack_bonus": 1.3,
        "morale_bonus": 1.2,
        "desc": "Ferocious in battle.",
    },
    "christian": {
        "trade_bonus": 1.3,
        "gunpowder": True,
        "desc": "Portuguese trade connections.",
    },
    "trade": {"treasury_rate": 1.5, "desc": "Strong trade networks."},
    "wealthy": {"treasury_rate": 1.8, "desc": "Exceptional wealth."},
    "castle_builders": {"defense_bonus": 1.5, "desc": "Superior fortifications."},
    "farmer_warriors": {"levy_bonus": 1.5, "desc": "Armed peasant levies."},
    "mountain_warfare": {"mountain_bonus": 1.5, "desc": "Expert in mountain terrain."},
    "winter_warfare": {"winter_bonus": 1.5, "desc": "Fights effectively in winter."},
    "horse_breeding": {"cavalry_bonus": 1.3, "desc": "Raises fine warhorses."},
    "pirate": {"naval_bonus": 1.3, "raid_rate": 1.5, "desc": "Pirate fleet."},
    "mercenary": {"hire_rate": 1.5, "desc": "Sells military service."},
    "religious": {
        "morale_bonus": 1.5,
        "fanatic": True,
        "desc": "Faith-driven warriors.",
    },
    "fanatic": {
        "morale_bonus": 1.8,
        "retreat_rate": 0.3,
        "desc": "Will not retreat easily.",
    },
    "peasant_army": {
        "levy_bonus": 2.0,
        "quality_penalty": 0.7,
        "desc": "Huge levies, lower quality.",
    },
    "independent": {"alliance_rate": 0.5, "desc": "Reluctant to ally."},
    "declining": {
        "military_decay": 1.5,
        "treasury_decay": 1.3,
        "desc": "Losing power over time.",
    },
    "opportunistic": {
        "opportunism": 1.5,
        "betrayal_rate": 0.5,
        "desc": "Switches sides readily.",
    },
    "traditional": {"tech_rate": 0.7, "morale_bonus": 1.1, "desc": "Slow to change."},
    "strategic": {"battle_bonus": 1.3, "desc": "Superior battle tactics."},
    "assassination": {"assassination_rate": 1.5, "desc": "Removes enemies quietly."},
    "guerilla": {"ambush_bonus": 1.5, "desc": "Excels at ambush warfare."},
    "frontier": {"expansion_rate": 1.3, "desc": "Pushes into new territory."},
    "charismatic": {"recruitment_bonus": 1.5, "desc": "Attracts followers."},
    "low_born": {"nobility_penalty": True, "desc": "Not of noble blood."},
    "legitimate": {"diplomacy_bonus": 2.0, "desc": "Legitimate authority."},
    "powerless": {"military_decay": 2.0, "desc": "No real military power."},
    "political": {"alliance_rate": 1.3, "desc": "Skilled political maneuvering."},
    "administrative": {"treasury_rate": 1.3, "desc": "Efficient administration."},
}

# ─────────────────────────────────────────────────────────────
# SIMULATION CONSTANTS
# ─────────────────────────────────────────────────────────────
SIM_TICK_DAYS = 1  # clan simulation runs every N game days
WAR_DECLARATION_THRESHOLD = 1.5  # military ratio needed to consider war
TRUCE_DURATION_DAYS = 90  # minimum truce length
ALLIANCE_BREAK_PENALTY = -50  # reputation hit for breaking alliance
BATTLE_RANDOM_FACTOR = 0.3  # randomness in battle outcomes (0-1)
SIEGE_DURATION_DAYS = 30  # base siege length for a castle
TERRITORY_UNREST_THRESHOLD = 30  # newly conquered provinces may rebel below this
